module.exports = [{
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'US',
    country_full_name: 'USA',
}, {
    mobile_length: [7],
    country_code: '297',
    country_short_name: 'AW',
    country_full_name: 'ABW',
}, {
    mobile_length: [9],
    country_code: '93',
    country_short_name: 'AF',
    country_full_name: 'AFG',
}, {
    mobile_length: [9],
    country_code: '244',
    country_short_name: 'AO',
    country_full_name: 'AGO',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'AI',
    country_full_name: 'AIA',
}, {
    mobile_length: [6, 7, 8],
    country_code: '358',
    country_short_name: 'AX',
    country_full_name: 'ALA',
}, {
    mobile_length: [9],
    country_code: '355',
    country_short_name: 'AL',
    country_full_name: 'ALB',
}, {
    mobile_length: [6],
    country_code: '376',
    country_short_name: 'AD',
    country_full_name: 'AND',
}, {
    mobile_length: [9],
    country_code: '971',
    country_short_name: 'AE',
    country_full_name: 'ARE',
}, {
    mobile_length: [6, 7, 8, 9],
    country_code: '54',
    country_short_name: 'AR',
    country_full_name: 'ARG',
}, {
    mobile_length: [8],
    country_code: '374',
    country_short_name: 'AM',
    country_full_name: 'ARM',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'AS',
    country_full_name: 'ASM',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'AG',
    country_full_name: 'ATG',
}, {
    mobile_length: [9],
    country_code: '61',
    country_short_name: 'AU',
    country_full_name: 'AUS',
}, {
    mobile_length: [10, 11, 12, 13, 14],
    country_code: '43',
    country_short_name: 'AT',
    country_full_name: 'AUT',
}, {
    mobile_length: [9],
    country_code: '994',
    country_short_name: 'AZ',
    country_full_name: 'AZE',
}, {
    mobile_length: [8],
    country_code: '257',
    country_short_name: 'BI',
    country_full_name: 'BDI',
}, {
    mobile_length: [9],
    country_code: '32',
    country_short_name: 'BE',
    country_full_name: 'BEL',
}, {
    mobile_length: [8],
    country_code: '229',
    country_short_name: 'BJ',
    country_full_name: 'BEN',
}, {
    mobile_length: [8],
    country_code: '226',
    country_short_name: 'BF',
    country_full_name: 'BFA',
}, {
    mobile_length: [8, 9, 10],
    country_code: '880',
    country_short_name: 'BD',
    country_full_name: 'BGD',
}, {
    mobile_length: [8, 9],
    country_code: '359',
    country_short_name: 'BG',
    country_full_name: 'BGR',
}, {
    mobile_length: [8],
    country_code: '973',
    country_short_name: 'BH',
    country_full_name: 'BHR',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'BS',
    country_full_name: 'BHS',
}, {
    mobile_length: [8],
    country_code: '387',
    country_short_name: 'BA',
    country_full_name: 'BIH',
}, {
    mobile_length: [9],
    country_code: '375',
    country_short_name: 'BY',
    country_full_name: 'BLR',
}, {
    mobile_length: [7],
    country_code: '501',
    country_short_name: 'BZ',
    country_full_name: 'BLZ',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'BM',
    country_full_name: 'BMU',
}, {
    mobile_length: [8],
    country_code: '591',
    country_short_name: 'BO',
    country_full_name: 'BOL',
}, {
    mobile_length: [10, 11],
    country_code: '55',
    country_short_name: 'BR',
    country_full_name: 'BRA',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'BB',
    country_full_name: 'BRB',
}, {
    mobile_length: [7],
    country_code: '673',
    country_short_name: 'BN',
    country_full_name: 'BRN',
}, {
    mobile_length: [8],
    country_code: '975',
    country_short_name: 'BT',
    country_full_name: 'BTN',
}, {
    mobile_length: [8],
    country_code: '267',
    country_short_name: 'BW',
    country_full_name: 'BWA',
}, {
    mobile_length: [8],
    country_code: '236',
    country_short_name: 'CF',
    country_full_name: 'CAF',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'CA',
    country_full_name: 'CAN',
}, {
    mobile_length: [9],
    country_code: '41',
    country_short_name: 'CH',
    country_full_name: 'CHE',
}, {
    mobile_length: [9],
    country_code: '56',
    country_short_name: 'CL',
    country_full_name: 'CHL',
}, {
    mobile_length: [11],
    country_code: '86',
    country_short_name: 'CN',
    country_full_name: 'CHN',
}, {
    mobile_length: [8],
    country_code: '225',
    country_short_name: 'CI',
    country_full_name: 'CIV',
}, {
    mobile_length: [8],
    country_code: '237',
    country_short_name: 'CM',
    country_full_name: 'CMR',
}, {
    mobile_length: [9],
    country_code: '243',
    country_short_name: 'CD',
    country_full_name: 'COD',
}, {
    mobile_length: [9],
    country_code: '242',
    country_short_name: 'CG',
    country_full_name: 'COG',
}, {
    mobile_length: [5],
    country_code: '682',
    country_short_name: 'CK',
    country_full_name: 'COK',
}, {
    mobile_length: [10],
    country_code: '57',
    country_short_name: 'CO',
    country_full_name: 'COL',
}, {
    mobile_length: [7],
    country_code: '269',
    country_short_name: 'KM',
    country_full_name: 'COM',
}, {
    mobile_length: [7],
    country_code: '238',
    country_short_name: 'CV',
    country_full_name: 'CPV',
}, {
    mobile_length: [8],
    country_code: '506',
    country_short_name: 'CR',
    country_full_name: 'CRI',
}, {
    mobile_length: [8],
    country_code: '53',
    country_short_name: 'CU',
    country_full_name: 'CUB',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'KY',
    country_full_name: 'CYM',
}, {
    mobile_length: [8],
    country_code: '357',
    country_short_name: 'CY',
    country_full_name: 'CYP',
}, {
    mobile_length: [9],
    country_code: '420',
    country_short_name: 'CZ',
    country_full_name: 'CZE',
}, {
    mobile_length: [10, 11],
    country_code: '49',
    country_short_name: 'DE',
    country_full_name: 'DEU',
}, {
    mobile_length: [8],
    country_code: '253',
    country_short_name: 'DJ',
    country_full_name: 'DJI',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'DM',
    country_full_name: 'DMA',
}, {
    mobile_length: [8],
    country_code: '45',
    country_short_name: 'DK',
    country_full_name: 'DNK',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'DO',
    country_full_name: 'DOM',
}, {
    mobile_length: [9],
    country_code: '213',
    country_short_name: 'DZ',
    country_full_name: 'DZA',
}, {
    mobile_length: [9],
    country_code: '593',
    country_short_name: 'EC',
    country_full_name: 'ECU',
}, {
    mobile_length: [10],
    country_code: '20',
    country_short_name: 'EG',
    country_full_name: 'EGY',
}, {
    mobile_length: [7],
    country_code: '291',
    country_short_name: 'ER',
    country_full_name: 'ERI',
}, {
    mobile_length: [9],
    country_code: '34',
    country_short_name: 'ES',
    country_full_name: 'ESP',
}, {
    mobile_length: [7, 8],
    country_code: '372',
    country_short_name: 'EE',
    country_full_name: 'EST',
}, {
    mobile_length: [9],
    country_code: '251',
    country_short_name: 'ET',
    country_full_name: 'ETH',
}, {
    mobile_length: [9, 10],
    country_code: '358',
    country_short_name: 'FI',
    country_full_name: 'FIN',
}, {
    mobile_length: [7],
    country_code: '679',
    country_short_name: 'FJ',
    country_full_name: 'FJI',
}, {
    mobile_length: [5],
    country_code: '500',
    country_short_name: 'FK',
    country_full_name: 'FLK',
}, {
    mobile_length: [9],
    country_code: '33',
    country_short_name: 'FR',
    country_full_name: 'FRA',
}, {
    mobile_length: [6],
    country_code: '298',
    country_short_name: 'FO',
    country_full_name: 'FRO',
}, {
    mobile_length: [7],
    country_code: '691',
    country_short_name: 'FM',
    country_full_name: 'FSM',
}, {
    mobile_length: [8],
    country_code: '241',
    country_short_name: 'GA',
    country_full_name: 'GAB',
}, {
    mobile_length: [10],
    country_code: '44',
    country_short_name: 'GB',
    country_full_name: 'GBR',
}, {
    mobile_length: [9],
    country_code: '995',
    country_short_name: 'GE',
    country_full_name: 'GEO',
}, {
    mobile_length: [9],
    country_code: '233',
    country_short_name: 'GH',
    country_full_name: 'GHA',
}, {
    mobile_length: [8],
    country_code: '350',
    country_short_name: 'GI',
    country_full_name: 'GIB',
}, {
    mobile_length: [8],
    country_code: '224',
    country_short_name: 'GN',
    country_full_name: 'GIN',
}, {
    mobile_length: [9],
    country_code: '590',
    country_short_name: 'GP',
    country_full_name: 'GLP',
}, {
    mobile_length: [7],
    country_code: '220',
    country_short_name: 'GM',
    country_full_name: 'GMB',
}, {
    mobile_length: [7],
    country_code: '245',
    country_short_name: 'GW',
    country_full_name: 'GNB',
}, {
    mobile_length: [9],
    country_code: '240',
    country_short_name: 'GQ',
    country_full_name: 'GNQ',
}, {
    mobile_length: [10],
    country_code: '30',
    country_short_name: 'GR',
    country_full_name: 'GRC',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'GD',
    country_full_name: 'GRD',
}, {
    mobile_length: [6],
    country_code: '299',
    country_short_name: 'GL',
    country_full_name: 'GRL',
}, {
    mobile_length: [8],
    country_code: '502',
    country_short_name: 'GT',
    country_full_name: 'GTM',
}, {
    mobile_length: [9],
    country_code: '594',
    country_short_name: 'GF',
    country_full_name: 'GUF',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'GU',
    country_full_name: 'GUM',
}, {
    mobile_length: [7],
    country_code: '592',
    country_short_name: 'GY',
    country_full_name: 'GUY',
}, {
    mobile_length: [8],
    country_code: '852',
    country_short_name: 'HK',
    country_full_name: 'HKG',
}, {
    mobile_length: [8],
    country_code: '504',
    country_short_name: 'HN',
    country_full_name: 'HND',
}, {
    mobile_length: [8, 9],
    country_code: '385',
    country_short_name: 'HR',
    country_full_name: 'HRV',
}, {
    mobile_length: [8],
    country_code: '509',
    country_short_name: 'HT',
    country_full_name: 'HTI',
}, {
    mobile_length: [9],
    country_code: '36',
    country_short_name: 'HU',
    country_full_name: 'HUN',
}, {
    mobile_length: [9, 10, 11, 12],
    country_code: '62',
    country_short_name: 'ID',
    country_full_name: 'IDN',
}, {
    mobile_length: [10],
    country_code: '91',
    country_short_name: 'IN',
    country_full_name: 'IND',
}, {
    mobile_length: [9],
    country_code: '353',
    country_short_name: 'IE',
    country_full_name: 'IRL',
}, {
    mobile_length: [10],
    country_code: '98',
    country_short_name: 'IR',
    country_full_name: 'IRN',
}, {
    mobile_length: [10],
    country_code: '964',
    country_short_name: 'IQ',
    country_full_name: 'IRQ',
}, {
    mobile_length: [7],
    country_code: '354',
    country_short_name: 'IS',
    country_full_name: 'ISL',
}, {
    mobile_length: [9],
    country_code: '972',
    country_short_name: 'IL',
    country_full_name: 'ISR',
}, {
    mobile_length: [10],
    country_code: '39',
    country_short_name: 'IT',
    country_full_name: 'ITA',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'JM',
    country_full_name: 'JAM',
}, {
    mobile_length: [9],
    country_code: '962',
    country_short_name: 'JO',
    country_full_name: 'JOR',
}, {
    mobile_length: [10],
    country_code: '81',
    country_short_name: 'JP',
    country_full_name: 'JPN',
}, {
    mobile_length: [10],
    country_code: '7',
    country_short_name: 'KZ',
    country_full_name: 'KAZ',
}, {
    mobile_length: [9],
    country_code: '254',
    country_short_name: 'KE',
    country_full_name: 'KEN',
}, {
    mobile_length: [9],
    country_code: '996',
    country_short_name: 'KG',
    country_full_name: 'KGZ',
}, {
    mobile_length: [8, 9],
    country_code: '855',
    country_short_name: 'KH',
    country_full_name: 'KHM',
}, {
    mobile_length: [5],
    country_code: '686',
    country_short_name: 'KI',
    country_full_name: 'KIR',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'KN',
    country_full_name: 'KNA',
}, {
    mobile_length: [9, 10],
    country_code: '82',
    country_short_name: 'KR',
    country_full_name: 'KOR',
}, {
    mobile_length: [8],
    country_code: '965',
    country_short_name: 'KW',
    country_full_name: 'KWT',
}, {
    mobile_length: [10],
    country_code: '856',
    country_short_name: 'LA',
    country_full_name: 'LAO',
}, {
    mobile_length: [7, 8],
    country_code: '961',
    country_short_name: 'LB',
    country_full_name: 'LBN',
}, {
    mobile_length: [7, 8],
    country_code: '231',
    country_short_name: 'LR',
    country_full_name: 'LBR',
}, {
    mobile_length: [9],
    country_code: '218',
    country_short_name: 'LY',
    country_full_name: 'LBY',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'LC',
    country_full_name: 'LCA',
}, {
    mobile_length: [7],
    country_code: '423',
    country_short_name: 'LI',
    country_full_name: 'LIE',
}, {
    mobile_length: [9],
    country_code: '94',
    country_short_name: 'LK',
    country_full_name: 'LKA',
}, {
    mobile_length: [8],
    country_code: '266',
    country_short_name: 'LS',
    country_full_name: 'LSO',
}, {
    mobile_length: [8],
    country_code: '370',
    country_short_name: 'LT',
    country_full_name: 'LTU',
}, {
    mobile_length: [9],
    country_code: '352',
    country_short_name: 'LU',
    country_full_name: 'LUX',
}, {
    mobile_length: [8],
    country_code: '371',
    country_short_name: 'LV',
    country_full_name: 'LVA',
}, {
    mobile_length: [8],
    country_code: '853',
    country_short_name: 'MO',
    country_full_name: 'MAC',
}, {
    mobile_length: [9],
    country_code: '212',
    country_short_name: 'MA',
    country_full_name: 'MAR',
}, {
    mobile_length: [8, 9],
    country_code: '377',
    country_short_name: 'MC',
    country_full_name: 'MCO',
}, {
    mobile_length: [8],
    country_code: '373',
    country_short_name: 'MD',
    country_full_name: 'MDA',
}, {
    mobile_length: [9],
    country_code: '261',
    country_short_name: 'MG',
    country_full_name: 'MDG',
}, {
    mobile_length: [7],
    country_code: '960',
    country_short_name: 'MV',
    country_full_name: 'MDV',
}, {
    mobile_length: [10, 11],
    country_code: '52',
    country_short_name: 'MX',
    country_full_name: 'MEX',
}, {
    mobile_length: [7],
    country_code: '692',
    country_short_name: 'MH',
    country_full_name: 'MHL',
}, {
    mobile_length: [8],
    country_code: '389',
    country_short_name: 'MK',
    country_full_name: 'MKD',
}, {
    mobile_length: [8],
    country_code: '223',
    country_short_name: 'ML',
    country_full_name: 'MLI',
}, {
    mobile_length: [8],
    country_code: '356',
    country_short_name: 'MT',
    country_full_name: 'MLT',
}, {
    mobile_length: [8],
    country_code: '95',
    country_short_name: 'MM',
    country_full_name: 'MMR',
}, {
    mobile_length: [8],
    country_code: '382',
    country_short_name: 'ME',
    country_full_name: 'MNE',
}, {
    mobile_length: [8],
    country_code: '976',
    country_short_name: 'MN',
    country_full_name: 'MNG',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'MP',
    country_full_name: 'MNP',
}, {
    mobile_length: [9],
    country_code: '258',
    country_short_name: 'MZ',
    country_full_name: 'MOZ',
}, {
    mobile_length: [8],
    country_code: '222',
    country_short_name: 'MR',
    country_full_name: 'MRT',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'MS',
    country_full_name: 'MSR',
}, {
    mobile_length: [9],
    country_code: '596',
    country_short_name: 'MQ',
    country_full_name: 'MTQ',
}, {
    mobile_length: [7],
    country_code: '230',
    country_short_name: 'MU',
    country_full_name: 'MUS',
}, {
    mobile_length: [9],
    country_code: '265',
    country_short_name: 'MW',
    country_full_name: 'MWI',
}, {
    mobile_length: [9, 10],
    country_code: '60',
    country_short_name: 'MY',
    country_full_name: 'MYS',
}, {
    mobile_length: [9],
    country_code: '269',
    country_short_name: 'YT',
    country_full_name: 'MYT',
}, {
    mobile_length: [9],
    country_code: '264',
    country_short_name: 'NA',
    country_full_name: 'NAM',
}, {
    mobile_length: [6],
    country_code: '687',
    country_short_name: 'NC',
    country_full_name: 'NCL',
}, {
    mobile_length: [8],
    country_code: '227',
    country_short_name: 'NE',
    country_full_name: 'NER',
}, {
    mobile_length: [5],
    country_code: '672',
    country_short_name: 'NF',
    country_full_name: 'NFK',
}, {
    mobile_length: [10],
    country_code: '234',
    country_short_name: 'NG',
    country_full_name: 'NGA',
}, {
    mobile_length: [8],
    country_code: '505',
    country_short_name: 'NI',
    country_full_name: 'NIC',
}, {
    mobile_length: [4],
    country_code: '683',
    country_short_name: 'NU',
    country_full_name: 'NIU',
}, {
    mobile_length: [9],
    country_code: '31',
    country_short_name: 'NL',
    country_full_name: 'NLD',
}, {
    mobile_length: [8],
    country_code: '47',
    country_short_name: 'NO',
    country_full_name: 'NOR',
}, {
    mobile_length: [10],
    country_code: '977',
    country_short_name: 'NP',
    country_full_name: 'NPL',
}, {
    mobile_length: [7],
    country_code: '674',
    country_short_name: 'NR',
    country_full_name: 'NRU',
}, {
    mobile_length: [8, 9, 10],
    country_code: '64',
    country_short_name: 'NZ',
    country_full_name: 'NZL',
}, {
    mobile_length: [8],
    country_code: '968',
    country_short_name: 'OM',
    country_full_name: 'OMN',
}, {
    mobile_length: [10],
    country_code: '92',
    country_short_name: 'PK',
    country_full_name: 'PAK',
}, {
    mobile_length: [8],
    country_code: '507',
    country_short_name: 'PA',
    country_full_name: 'PAN',
}, {
    mobile_length: [9],
    country_code: '51',
    country_short_name: 'PE',
    country_full_name: 'PER',
}, {
    mobile_length: [10],
    country_code: '63',
    country_short_name: 'PH',
    country_full_name: 'PHL',
}, {
    mobile_length: [7],
    country_code: '680',
    country_short_name: 'PW',
    country_full_name: 'PLW',
}, {
    mobile_length: [8],
    country_code: '675',
    country_short_name: 'PG',
    country_full_name: 'PNG',
}, {
    mobile_length: [9],
    country_code: '48',
    country_short_name: 'PL',
    country_full_name: 'POL',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'PR',
    country_full_name: 'PRI',
}, {
    mobile_length: [9],
    country_code: '351',
    country_short_name: 'PT',
    country_full_name: 'PRT',
}, {
    mobile_length: [9],
    country_code: '595',
    country_short_name: 'PY',
    country_full_name: 'PRY',
}, {
    mobile_length: [9],
    country_code: '970',
    country_short_name: 'PS',
    country_full_name: 'PSE',
}, {
    mobile_length: [6],
    country_code: '689',
    country_short_name: 'PF',
    country_full_name: 'PYF',
}, {
    mobile_length: [8],
    country_code: '974',
    country_short_name: 'QA',
    country_full_name: 'QAT',
}, {
    mobile_length: [9],
    country_code: '262',
    country_short_name: 'RE',
    country_full_name: 'REU',
}, {
    mobile_length: [9],
    country_code: '40',
    country_short_name: 'RO',
    country_full_name: 'ROU',
}, {
    mobile_length: [10],
    country_code: '7',
    country_short_name: 'RU',
    country_full_name: 'RUS',
}, {
    mobile_length: [9],
    country_code: '250',
    country_short_name: 'RW',
    country_full_name: 'RWA',
}, {
    mobile_length: [9],
    country_code: '966',
    country_short_name: 'SA',
    country_full_name: 'SAU',
}, {
    mobile_length: [9],
    country_code: '249',
    country_short_name: 'SD',
    country_full_name: 'SDN',
}, {
    mobile_length: [9],
    country_code: '221',
    country_short_name: 'SN',
    country_full_name: 'SEN',
}, {
    mobile_length: [8],
    country_code: '65',
    country_short_name: 'SG',
    country_full_name: 'SGP',
}, {
    mobile_length: [4],
    country_code: '290',
    country_short_name: 'SH',
    country_full_name: 'SHN',
}, {
    mobile_length: [8],
    country_code: '47',
    country_short_name: 'SJ',
    country_full_name: 'SJM',
}, {
    mobile_length: [7],
    country_code: '677',
    country_short_name: 'SB',
    country_full_name: 'SLB',
}, {
    mobile_length: [8],
    country_code: '232',
    country_short_name: 'SL',
    country_full_name: 'SLE',
}, {
    mobile_length: [8],
    country_code: '503',
    country_short_name: 'SV',
    country_full_name: 'SLV',
}, {
    mobile_length: [10],
    country_code: '378',
    country_short_name: 'SM',
    country_full_name: 'SMR',
}, {
    mobile_length: [8],
    country_code: '252',
    country_short_name: 'SO',
    country_full_name: 'SOM',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'SX',
    country_full_name: 'SXM',
}, {
    mobile_length: [6],
    country_code: '508',
    country_short_name: 'PM',
    country_full_name: 'SPM',
}, {
    mobile_length: [8, 9],
    country_code: '381',
    country_short_name: 'RS',
    country_full_name: 'SRB',
}, {
    mobile_length: [7],
    country_code: '239',
    country_short_name: 'ST',
    country_full_name: 'STP',
}, {
    mobile_length: [7],
    country_code: '597',
    country_short_name: 'SR',
    country_full_name: 'SUR',
}, {
    mobile_length: [9],
    country_code: '421',
    country_short_name: 'SK',
    country_full_name: 'SVK',
}, {
    mobile_length: [8],
    country_code: '386',
    country_short_name: 'SI',
    country_full_name: 'SVN',
}, {
    mobile_length: [9],
    country_code: '46',
    country_short_name: 'SE',
    country_full_name: 'SWE',
}, {
    mobile_length: [7],
    country_code: '248',
    country_short_name: 'SC',
    country_full_name: 'SYC',
}, {
    mobile_length: [9],
    country_code: '963',
    country_short_name: 'SY',
    country_full_name: 'SYR',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'TC',
    country_full_name: 'TCA',
}, {
    mobile_length: [8],
    country_code: '235',
    country_short_name: 'TD',
    country_full_name: 'TCD',
}, {
    mobile_length: [8],
    country_code: '228',
    country_short_name: 'TG',
    country_full_name: 'TGO',
}, {
    mobile_length: [9],
    country_code: '66',
    country_short_name: 'TH',
    country_full_name: 'THA',
}, {
    mobile_length: [9],
    country_code: '992',
    country_short_name: 'TJ',
    country_full_name: 'TJK',
}, {
    mobile_length: [4],
    country_code: '690',
    country_short_name: 'TK',
    country_full_name: 'TKL',
}, {
    mobile_length: [8],
    country_code: '993',
    country_short_name: 'TM',
    country_full_name: 'TKM',
}, {
    mobile_length: [8],
    country_code: '670',
    country_short_name: 'TL',
    country_full_name: 'TLS',
}, {
    mobile_length: [5],
    country_code: '676',
    country_short_name: 'TO',
    country_full_name: 'TON',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'TT',
    country_full_name: 'TTO',
}, {
    mobile_length: [8],
    country_code: '216',
    country_short_name: 'TN',
    country_full_name: 'TUN',
}, {
    mobile_length: [10],
    country_code: '90',
    country_short_name: 'TR',
    country_full_name: 'TUR',
}, {
    mobile_length: [5],
    country_code: '688',
    country_short_name: 'TV',
    country_full_name: 'TUV',
}, {
    mobile_length: [9],
    country_code: '886',
    country_short_name: 'TW',
    country_full_name: 'TWN',
}, {
    mobile_length: [9],
    country_code: '255',
    country_short_name: 'TZ',
    country_full_name: 'TZA',
}, {
    mobile_length: [9],
    country_code: '256',
    country_short_name: 'UG',
    country_full_name: 'UGA',
}, {
    mobile_length: [9],
    country_code: '380',
    country_short_name: 'UA',
    country_full_name: 'UKR',
}, {
    mobile_length: [8],
    country_code: '598',
    country_short_name: 'UY',
    country_full_name: 'URY',
}, {
    mobile_length: [9],
    country_code: '998',
    country_short_name: 'UZ',
    country_full_name: 'UZB',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'VC',
    country_full_name: 'VCT',
}, {
    mobile_length: [10],
    country_code: '58',
    country_short_name: 'VE',
    country_full_name: 'VEN',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'VG',
    country_full_name: 'VGB',
}, {
    mobile_length: [10],
    country_code: '1',
    country_short_name: 'VI',
    country_full_name: 'VIR',
}, {
    mobile_length: [9, 10],
    country_code: '84',
    country_short_name: 'VN',
    country_full_name: 'VNM',
}, {
    mobile_length: [7],
    country_code: '678',
    country_short_name: 'VU',
    country_full_name: 'VUT',
}, {
    mobile_length: [6],
    country_code: '681',
    country_short_name: 'WF',
    country_full_name: 'WLF',
}, {
    mobile_length: [7],
    country_code: '685',
    country_short_name: 'WS',
    country_full_name: 'WSM',
}, {
    mobile_length: [9],
    country_code: '967',
    country_short_name: 'YE',
    country_full_name: 'YEM',
}, {
    mobile_length: [9],
    country_code: '27',
    country_short_name: 'ZA',
    country_full_name: 'ZAF',
}, {
    mobile_length: [9],
    country_code: '260',
    country_short_name: 'ZM',
    country_full_name: 'ZMB',
}, {
    mobile_length: [9],
    country_code: '263',
    country_short_name: 'ZW',
    country_full_name: 'ZWE',
}]
